#!/usr/bin/python3
import sys, argparse, uuid, lxml.etree, json, libvirt, nixvirt

parser = argparse.ArgumentParser(prog='nixvirt-module-helper',description='Define and control a collection of libvirt objects idempotently.')
parser.add_argument('-v', '--verbose', action='store_true', help='report actions to stderr')
parser.add_argument('--connect', action='store', required=True, metavar='URI', help='connection URI (e.g. qemu:///session)')
parser.add_argument('settingspath', action='store', metavar='PATH', help='path to JSON file of settings')
args = parser.parse_args()

with open(args.settingspath,"r") as f:
    settings = json.load(f)

class TypeSpec:
    def __init__(self,session,type,itemlist):
        self.oc = nixvirt.getObjectConnection(session,type)
        self.specList = [nixvirt.ObjectSpec.fromDefinitionFile(self.oc,item["definition"],item.get("active")) for item in itemlist]

    def deleteOld(self):
        allObjects = self.oc.getAll()
        keepUUIDs = [objspec.specUUID for objspec in self.specList]
        for object in allObjects:
            if object.uuid in keepUUIDs:
                pass
            else:
                object.undefine()

    def define(self):
        defineResults = {}
        for objspec in self.specList:
            defineResults[objspec.specName] = objspec.define()
        return defineResults

    def setActive(self):
        for objspec in self.specList:
            objspec.setActive()

try:
    session = nixvirt.Session(args.connect,args.verbose)

    types = [("network","networks"),("pool","pools"),("domain","domains")]
    defineResults = {}

    typeSpecs = []
    for (type,key) in types:
        itemlist = settings.get(key)
        if itemlist is not None:
            typeSpecs.append(TypeSpec(session,type,itemlist))

    # delete old stuff
    for typeSpec in typeSpecs:
        typeSpec.deleteOld()

    # define new stuff
    for typeSpec in typeSpecs:
        defineResults[typeSpec.type] = typeSpec.define()

    # do activation
    for typeSpec in typeSpecs:
        typeSpec.setActive()
    
    # reset network for Domains that had a network change
    network_results = defineResults["network"]
    domain_results = defineResults["domain"]
    networkSession = nixvirt.getObjectConnection(session,"network")
    domainSession = nixvirt.getObjectConnection(session,"network")
    for network in network_results:
        result = network_results[network]

        if result != "changed": continue
        network = networkSession.fromNameOrNone(network)
        for dependent in network._getDependents(network):
            name = dependent.descriptionXMLETree().find("name").text
            if name in result and result[name] == "unchanged":
                 


except libvirt.libvirtError as err:
    print ("NixVirt: libvirt error:", err, file=sys.stderr)
    sys.exit(1)

except lxml.etree.XMLSyntaxError as err:
    print ("NixVirt: XML error:", err, file=sys.stderr)
    sys.exit(1)
